[2024-03-06T14:27:48.986+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_welcome scheduled__2024-03-05T11:00:00+00:00 [queued]>
[2024-03-06T14:27:48.999+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_welcome scheduled__2024-03-05T11:00:00+00:00 [queued]>
[2024-03-06T14:27:49.000+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T14:27:49.045+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): print_welcome> on 2024-03-05 11:00:00+00:00
[2024-03-06T14:27:49.049+0000] {standard_task_runner.py:60} INFO - Started process 167 to run task
[2024-03-06T14:27:49.052+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_welcome', 'scheduled__2024-03-05T11:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/welcome.py', '--cfg-path', '/tmp/tmp6jigph29']
[2024-03-06T14:27:49.055+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask print_welcome
[2024-03-06T14:27:49.152+0000] {task_command.py:423} INFO - Running <TaskInstance: welcome_dag.print_welcome scheduled__2024-03-05T11:00:00+00:00 [running]> on host 52a258c822d6
[2024-03-06T14:27:49.285+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_welcome' AIRFLOW_CTX_EXECUTION_DATE='2024-03-05T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-05T11:00:00+00:00'
[2024-03-06T14:27:49.287+0000] {logging_mixin.py:188} INFO - Welcome to Airflow!
[2024-03-06T14:27:49.291+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/welcome.py", line 36, in print_welcome
    execute_file("D:\Bootcamp\DE\IncrementalUpdates.py")
  File "/opt/airflow/dags/welcome.py", line 15, in execute_file
    result = subprocess.run(["python", file_path], capture_output=True, text=True, check=True, cwd="D:\Bootcamp\DE")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Bootcamp\\DE'
[2024-03-06T14:27:49.309+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=welcome_dag, task_id=print_welcome, execution_date=20240305T110000, start_date=20240306T142748, end_date=20240306T142749
[2024-03-06T14:27:49.351+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task print_welcome ([Errno 2] No such file or directory: 'D:\\Bootcamp\\DE'; 167)
[2024-03-06T14:27:49.387+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T14:27:49.433+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
